gbprod/substitute.nvim

- .github/workflows/panvimdoc.yml
- doc/substitute-nvim.txt
- lua/substitute.lua
- lua/substitute/range.lua
- lua/substitute/utils.lua
- spec/spec.vim
- spec/substitute/range_spec.lua
- spec/substitute/utils_spec.lua
- spec/substitute_spec.lua
https://github.com/gbprod/substitute.nvim/issues/2
> feat: improve get_regions to select ctrl-v selections

- README.md
- doc/substitute-nvim.txt
- lua/substitute/config.lua
- lua/substitute/range.lua
> feat(range): introduce motion1 and motion2 options

- README.md
- lua/substitute.lua
- spec/spec.vim
- spec/substitute_spec.lua
> fix(substitute): use vim.v.count for substitute operator

- README.md
- lua/substitute.lua
> feat(substitute): allow to set register and count as operator option

- README.md
- lua/substitute/config.lua
- lua/substitute/range.lua
> feat(range): introduce register management for range replacement

- README.md
- lua/substitute/config.lua
- lua/substitute/range.lua
> feat(range): introduce group_substituted_text option

- README.md
- lua/substitute/range.lua
- spec/spec.vim
> refactor!: use vim.keymap.set and drop 0.6.0 support

- lua/substitute/range.lua
- spec/substitute/range_spec.lua
> fix(range): change feedkey mode to avoid matchadd issues

- lua/substitute.lua
- lua/substitute/exchange.lua
- lua/substitute/range.lua
- lua/substitute/utils.lua
- spec/substitute/utils_spec.lua
> refactor(substitute): use vmode for get_text and substitute_text

- lua/substitute.lua
> fix: use nvim_set_hl instead of highlight.link

- README.md
- lua/substitute/config.lua
- lua/substitute/exchange.lua
> feat(exchange): allow use <esc> key to cancel exchange

- README.md
- lua/substitute/exchange.lua
> fix(exchange): properly remap <esc> if lua callback

- lua/substitute.lua
In order to make it works with yanky integration
Ref: #48
> fix: use text-objects for visual substitution

- lua/substitute.lua
- lua/substitute/exchange.lua
- lua/substitute/range.lua
> fix: do not remap keys on feedkeys

- lua/substitute.lua
- lua/substitute/exchange.lua
- lua/substitute/range.lua
> fix: restore feedkeys

- .gitignore
- README.md
- lua/substitute.lua
- lua/substitute/config.lua
- lua/substitute/utils.lua
> feat: highlight substituted text

- lua/substitute/utils.lua
> fix: allow substitute in empty blocks

- lua/substitute/config.lua
- lua/substitute/exchange.lua
> feat(exchange): preserve cursor position on exchange (with option)

- README.md
- lua/substitute.lua
- lua/substitute/config.lua
> feat(substitute): add option to preserve cursor position

- lua/substitute/range.lua
> fix(range): always apply matchadd

- lua/substitute.lua
- lua/substitute/utils.lua
> fix(substitute): correctly substitute text with unicode

- README.md
- lua/substitute/config.lua
- lua/substitute/range.lua
> feat(range): introduce auto apply option

- README.md
- lua/substitute/config.lua
- lua/substitute/range.lua
> feat(range): introduce the cursor position config
